### PR TITLE
Update Korean.isl

### PR DESCRIPTION
**Pull request by VenusGirl**

### CODE REVIEW

**Comment by martijnlaan** [comment]
Thanks. Why did you remove the names of all previous contributors? Can you restore that part?

**Comment by VenusGirl** [comment]
As I tried to make it and use it in the installation program, there were so many mistakes such as spelling, wrong translation, etc., and the meaning was not conveyed well, so I translated it completely into the original English without referring to the previous contributor's translation.

Should there be a history of previous contributors?

If that part is necessary and necessary, I will revise it.

**Review by VenusGirl — COMMENTED** [review]
It is a translation that is as faithful as possible to the original English text without omission.

**Comment by martijnlaan** [comment]
Thanks. I'm currently away from home and will merge this PR when I get back.

**Review by kristinWalker1991 — APPROVED** [review]

**Review by kristinWalker1991 — CHANGES_REQUESTED** [review]
Files/Languages/Unofficial/Korean.isl

**Review by kristinWalker1991 — COMMENTED** [review]
[]()Files/Languages/Unofficial/Korean.isl

**Pull request closed without merging**
