### PR TITLE
Improved danish translation

### PR DESCRIPTION
**Pull request by scootergrisen**
I have made improvements to the danish translation.

I have contacted the current maintainer of the danish translation but the persons does not want to communicate.

### CODE REVIEW

**Comment by martijnlaan** [comment]
Thanks. I've contacted Thomas and he will be looking through your suggestions and provide an update (if needed).

**Comment by scootergrisen** [comment]
I would like another review of the changes that i have suggested in this commit.

I spend a lot of time working on improving the translation, but a lot of my improvements have been discarded, even though i correct something that is wrongly translated into something that is correct translated.

My name have been removed from the file so I'm not being credited for my work.

Update changes from Default.isl that i have made, like comments have also been discarded.

Special Windows word that i have corrected to use the same words as microsoft uses in Windows have also been discharded. Like the words for the start hurtigt and quick launch.

**Comment by martijnlaan** [comment]
Any suggestions you have should be sent to Thomas.

**Comment by scootergrisen** [comment]
From my first message:

    I have contacted the current maintainer of the danish translation but the persons does not want to communicate.

**Comment by scootergrisen** [comment]
So where do we go from here if the current maintainer of the translation does not want to communicate?

**Comment by martijnlaan** [comment]
I don't know why you guys are unable to communicate but you will need to stand up and fix it. So please, start talking to each other. From my own experience I know that Thomas does read his mail and replies to it. Posting more stuff here is pointless, I don't know Danish, so please don't do that.

**Comment by scootergrisen** [comment]
I have written 2 times already to him. And gotten 2 answers.

He wants personal information about me and says he do not want to communicate unless i give him this information. Which he is not going to get. I don't see any reason why i should give out personal information about my self to contribute to this project.

I have not come across this problem in any of the other projects i work on.

**Comment by martijnlaan** [comment]
Can you email me your email address so I can send an email to you both about this?

**Comment by thvedel** [comment]
Hi all, 

I am the author of the official Danish translation. I want to correct a few incorrect informations above.

Firstly I have never refused to work together with scootergrisen. He firstly contacted me a couple of months ago. I always want to know who I am working with, but when I asked scootergrisen to tell me who he actually is he went silent, and I never received his suggested changes until Martijn sent them to me a couple of weeks ago.

Secondly I simply don't agree in all the suggested changes that I received via Martijn. A lot of the suggestions are indeed improvements and they have already been merged them into the next version of the official translation. But in my opinion there were also changes that I think should not be approved.

I have now received a new set of suggestions from scootergrisen, and I will work through them as well.

Finally, I think that it is really odd that we have to communicate in this way instead of scootergrisen simply communicating directly to me.

Best regards
Thomas

**Pull request closed without merging**
