### PR TITLE
correct spelling

### PR DESCRIPTION
**Pull request by CennoxX**
added changes according to https://github.com/winscp/winscp/pull/16#issuecomment-717236780

### CODE REVIEW

**Comment by martijnlaan** [comment]
Thanks but see https://jrsoftware.org/files/istrans/: If you have fixes, comments or suggestions about a particular translation, please contact its maintainer. If he or she doesn't reply or doesn't want to include your changes, use the forum to discuss this.

**Comment by CennoxX** [comment]
I only submitted this fix because @martinprikryl asked me to. It's not my problem if you keep your spelling mistakes.

**Comment by martinprikryl** [comment]
> I only submitted this fix because @martinprikryl asked me to. It's not my problem if you keep your spelling mistakes.

Sorry, I didn't realize that Inno Setup has policies for contributions. I'll handle this myself.

**Comment by martijnlaan** [comment]
@martinprikryl Fyi, I've sent him a notification yesterday too since @CennoxX didn't want to do this.

**Comment by jensbrand** [comment]
I will check this as soon as possible.

**Comment by jensbrand** [comment]
@martijnlaan Hello Martijn, I checked this pullrequest, the changes are correct. Can you merge this PR directly or should I create another one?

**Comment by martijnlaan** [comment]
@jensbrand I will handle it, thanks.

**Pull request closed without merging**
