### PR TITLE
Updated Ukrainian translation

### PR DESCRIPTION
**Pull request by leserg73**
Reviewed and updated Ukrainian translation.

### CODE REVIEW

**Comment by martijnlaan** [comment]
Thanks! I will register you as the new maintainer, ok?

**Comment by leserg73** [comment]
Ok,

**Comment by martijnlaan** [comment]
Can you please add your name and email to the file?

**Comment by jordanrussell** [comment]
Please also use UTF-8 encoding if possible.

**Comment by leserg73** [comment]
> Can you please add your name and email to the file? For example leserg73 and [5IM0f0R@ukr.net](mailto:5IM0f0R@ukr.net)
> Please also use UTF-8 encoding if possible.

Done.

**Pull request closed without merging**
