### PR TITLE
Update Italian.isl

### PR DESCRIPTION
**Pull request by bovirus**
Update Italian language

### CODE REVIEW

**Comment by martijnlaan** [comment]
Thanks but see http://jrsoftware.org/files/istrans/: If you have fixes, comments or suggestions about a particular translation, please contact its maintainer. If he or she doesn't reply or doesn't want to include your changes, use the jrsoftware.innosetup.translations newsgroup to discuss this (web-based interface available).

**Comment by bovirus** [comment]
@martijnlaan

I'm a professional translator that works free of charge for many freeware/software projects (Filezilla/Poedit/Avant Brwoser/DVDFab suite/VSO Sofwtare suite/and many others) about Italian language translation.

I checked that many software in the world that use your installer have the same problem on Italian language because the problem is related to InnoSetup Italian language file.
I found in Italian language (ISL file) a lot of problems like

- String too long (the name of the program in some installer are truncated) and not tested in place. Ex. "Benvenuto nell'installazione di ..." instead "Installazione di..."
- Strings without a sense in Italiam ("%s sul web" should be "Sito web di %s")
- Errors that seems didn't made from a really Italian translator that is Italian.

There are some Italian translators that many times didn't knows the alphabet of pc/internet terms and use many times words that are not reflecting the pc/internet Italian words.

I'm quite surprise that no one made you a feedback about that.
As you can see there is no activity on the newsgroup on Italian language and also I sent many email to the translator author (as in the header of the language) but I didn't receive any answer.

I believe that you should select a language maintainer that is really a maintainer.

A maintainer should make any check (also in place), update the language and so on.
I believe that if the maintainer didn't make live the Language you should select another language maintainer.

I spent part of my spare time to make a service for a lot of Italian users and many software makers that are using your installer and now you answered me that I have to contact someone that didn't answer and post in a newsgroup where no one partecipate about Italian language.

I believe that if no one works on Italian language you should change the Italian language maintainer and I propose myself for it.

Thanks. Bye.

**Comment by ajtruckle** [comment]
I don't see the problem of using GitHub to discuss these things instead of the newsgroup. I have found several unofficial languages out of date for long time. 

Well done for coming forward. Perhaps Jordan can accept your kindness to support his installer as a active maintainer. 

My two cents. 😀😀

**Comment by bovirus** [comment]
@martijnlaan 
Thanks for the reply. 
How can help you about Italian language?
Who is the person to contact to become an active Italian language maintainer?

**Comment by ajtruckle** [comment]
You need to do it here:

http://news.jrsoftware.org/read/thread.php?group=jrsoftware.innosetup.translations

Sent from my iPhone

On 25 Sep 2017, at 14:31, ROBERTO <notifications@github.com<mailto:notifications@github.com>> wrote:


@martijnlaan<https://github.com/martijnlaan>
Thanks for the reply.
How can help you about Italian language?
Who is the person to contact to become an active Italian language maintainer?

**Comment by ajtruckle** [comment]
https://github.com/jrsoftware/issrc/blob/master/CONTRIBUTING.md

Sent from my iPhone

On 25 Sep 2017, at 14:31, ROBERTO <notifications@github.com<mailto:notifications@github.com>> wrote:


@martijnlaan<https://github.com/martijnlaan>
Thanks for the reply.
How can help you about Italian language?
Who is the person to contact to become an active Italian language maintainer?

**Comment by bovirus** [comment]
@martijnlaan 

About git I posted it my pullup request for a new Italian language update.

**Comment by martijnlaan** [comment]
> Who is the person to contact to become an active Italian language maintainer?

See http://jrsoftware.org/files/istrans/ for the name and email adress. Please discuss your changes with him and if you guys would like you to become the new maintainer or not.

**Comment by bovirus** [comment]
@martijnlaan 
I sent again the email to the original Italian translation author.
I hope that could be anwsered as soon as possible.
How can contact Jordan?

**Comment by martijnlaan** [comment]
You don't need to contact Jordan, just let me know what the result is after you talked to Rinaldo.

**Comment by bovirus** [comment]
@martijnlaan

No asnwer by latest translator author (ref. in the isl language file).

**Comment by martijnlaan** [comment]
I will send him a mail myself too and if theres no reply in 3 weeks you can take over.

**Comment by bovirus** [comment]
Thanks.
I will wait up to three weeks.

**Comment by bovirus** [comment]
@martijnlaan 

Did you get any answer?

**Comment by martijnlaan** [comment]
No I haven't. Please put your name and email address in the file + make it an ANSI file instead of UTF8 and then you can take over as the maintainer. Thanks in advance.

**Comment by bovirus** [comment]
Thanks for the opportunity.
I attached the file with my email reference.
The text file is in ANSI text format (checked with Notepad++).

[InnoSetup-5.5.3-Italian-language-2017.10.24.zip](https://github.com/jrsoftware/issrc/files/1409857/InnoSetup-5.5.3-Italian-language-2017.10.24.zip)

**Comment by martijnlaan** [comment]
Thanks but can you put your name in it as well? Can be bovirus or anything else.

**Comment by bovirus** [comment]
Yes. My nickname is bovirus.
I updated the language file in previous post.
I hope that is right. Thanks.

**Comment by bovirus** [comment]
@martijnlaan 
The language pullup request is again in place.
Could you please update it?
Thanks.

**Comment by martijnlaan** [comment]
Thanks. I didn't see any commit to add your name, but I saw you did update the zip file for that so I took if from there.

**Comment by bovirus** [comment]
@martijnlaan 

I have to push some small changes.
Which is the right text format (ANSI or UTF-8)?
When i try to edit the file Github detected and post this message

**We've detected the file encoding as ISO-8859-1. When you commit changes we will transcode it to UTF-8.** 

Is it right?
How can post the text strings directly as UTF-8 that it's universal?

Thanks. Bye.

**Comment by martijnlaan** [comment]
The file should be ANSI. Can you change that? If Github doesn't work for you please use http://jrsoftware.org/files/istrans/send2.php

**Comment by bovirus** [comment]
Hi.
Github works for me.

I just mentioned it because Github report that (for any languages - I tested also with Japanese...).
I posted the new file using ANSI text codification.
But I'm not sure what kind of changes (from ANSI to UTF-8) Github did on it.

I will send the new Italian translation file via

http://jrsoftware.org/files/istrans/send2.php

**Comment by bovirus** [comment]
@martijnlaan 

I checked that all language files installed by standard Inno Setup 5.5.9 are text file in ANSI  text format.

Are there differences about text file format for .ISL language files installed by Inno Setup standard or Unicode? Both version are using .isl language file in ANSI text format?

The file that the user can download as .isl language update from web page

http://www.jrsoftware.org/files/istrans/

are in UTF-8 text format.

This kind of language files with UTF-8 text format create problem on accented letter on standard Inno Setup.

Why do you enable download of .isl file as UTF-8 text format instead of ANSI text format?

Thanks.

**Comment by martijnlaan** [comment]
The files downloaded are not UTF8, see for example https://raw.github.com/jrsoftware/issrc/master/Files/Languages/Dutch.isl unless the language requires Unicode.

I do see that Italian is UTF8, this is wrong. It must mean you submitted it as UTF8 since I dont make any changes myself. I checked and the one you submitted with #254 is UTF8, see https://github.com/bovirus/issrc/raw/09660cf9ba2709e1855c7dc54c66a73815eea687/Files/Languages/Italian.isl

Can you submit a new one which is ANSI again?

**Comment by bovirus** [comment]
Ok. Thanks for the clarification.

I will upload a new language file version but ANSI.

Thanks.

**Pull request closed without merging**
