### PR TITLE
Update LZMA SDK to the latest version, currently is 19.00

### PR DESCRIPTION
**Pull request by wangwenx190**
Tested with Inno Setup 6.0.0-beta (downloaded from jrsoftware.org) and islzma.dll islzma32.exe islzma64.exe compiled by Visual Studio 2017 by myself, everything works normal.

### CODE REVIEW

**Comment by wangwenx190** [comment]
I can also provide the compiled files if you don't have VS2017, but you will have to sign the files yourself.

**Comment by wangwenx190** [comment]
I suggest you update the https://github.com/jrsoftware/iscompress repo as well, it has not been updated since 2010. The code is too old nowadays.

**Comment by wangwenx190** [comment]
Should ISLzma2Dec.obj and ISLzmaDec.obj be updated as well? I saw you built them through Borland C++ Builder 6, can I use MSVC2017 to do it?

**Comment by wangwenx190** [comment]
I generated the two obj files using MSVC2017, I don't know whether they are compatible with Delphi or not, maybe you should test it.

**Comment by martijnlaan** [comment]
Thanks!

**Comment by martijnlaan** [comment]
> 
> 
> I generated the two obj files using MSVC2017, I don't know whether they are compatible with Delphi or not, maybe you should test it.

I seems highly unlikely to me that they are compatible. Note that C++ Builder is available for free at https://www.embarcadero.com/products/cbuilder/starter and there's also such a version of Delphi.

**Comment by wangwenx190** [comment]
> 
> 
> > I generated the two obj files using MSVC2017, I don't know whether they are compatible with Delphi or not, maybe you should test it.
> 
> I seems highly unlikely to me that they are compatible. Note that C++ Builder is available for free at https://www.embarcadero.com/products/cbuilder/starter and there's also such a version of Delphi.

Sorry that I have installed so many C++ compilers and I don't want to install a new one. You can generate the two files yourself.

**Comment by martijnlaan** [comment]
Ok, no problem. Note: I don't have C++ Builder installed myself either and also need to look at some other IS6 issues first, so it will take some time before I can pick up this pull request.

**Comment by martijnlaan** [comment]
Jordan pointed out to me that the pull request adds files that were deliberately not committed before (like MtDec.*) because they would never be used by IS. Can you remove those? TIA.

**Comment by wangwenx190** [comment]
MtDec.h and MtDec.c were removed but the MtCoder.h and MtCoder.c were modified as well to let LZMA SDK succeed to compile. And I reverted the "Update obj files" commit.

**Comment by wangwenx190** [comment]
@martijnlaan Any news? Is it possible to get this PR merged in the near future?

**Comment by martijnlaan** [comment]
No:

- Last week I discovered that Delphi Community Edition and C++ Builder Community Edition can't even be installed at the same time, which complicates things more.
- There here also don't seem to be any meaningful benefit to updating the SDK, leaving only the risk something breaks because of it.

Sorry.

**Comment by mfriedrich74** [comment]
Time to migrate to Lazarus?

**Comment by martijnlaan** [comment]
Why? Lazarus doesn't support C++ right?

**Comment by wangwenx190** [comment]
> 
> 
> No:
> 
>     * Last week I discovered that Delphi Community Edition and C++ Builder Community Edition can't even be installed at the same time, which complicates things more.
> 
>     * There here also don't seem to be any meaningful benefit to updating the SDK, leaving only the risk something breaks because of it.
> 
> 
> Sorry.

Yes, you are right. I'm OK with it. But I think after deciding not to merge this PR, you should tell me about it earlier.

**Comment by martijnlaan** [comment]
I hadn't actually decided on such a thing myself yet. Still, I'm sorry you feel this way since I appreciate your earlier contributions.

Having said that, I think you set this pull request up for failure yourself. It requires some significant effort before it can be merged but you have indicated that you don't want to put in this effort yourself nor did you make it clear why it's worth the effort for anyone else. Additionally you didn't discuss any of this before hand.

I think this happened because it didn't really take a lot of time to create this pull request? You just copied over the SDK, added all files and did some quick edits to make it compile without removing things that shouldn't be there and without fixing the things that are missing, right?

So I think that you would have to agree this was just a low effort pull request. So lesson learned about that, at least for me, and hopefully no hard feelings.

**Comment by wangwenx190** [comment]
> 
> 
> I hadn't actually decided on such a thing myself yet. Still, I'm sorry you feel this way since I appreciate your earlier contributions.
> 
I may misunderstand you yesterday, I apologize if you feel uncomfortable.
> Having said that, I think you set this pull request up for failure yourself. It requires some significant effort before it can be merged but you have indicated that you don't want to put in this effort yourself nor did you make it clear why it's worth the effort for anyone else. Additionally you didn't discuss any of this before hand.
> 
I'm not familiar with Delphi, I'm not even a professional programmer, update the lzma sdk is all I can do for Inno Setup currently.
> I think this happened because it didn't really take a lot of time to create this pull request? You just copied over the SDK, added all files and did some quick edits to make it compile without removing things that shouldn't be there and without fixing the things that are missing, right?
> 
Actually, it didn't cost me much time indeed, but I did some tests and it works just fine. I didn't remove these files because I thought they may be useful and I didn't dare to delete them. I didn't find anything missing, so I didn't fix anything either.
> So I think that you would have to agree this was just a low effort pull request. So lesson learned about that, at least for me, and hopefully no hard feelings.
>
Yes, you are right. Maybe my words were  a little unfriendly and make you feel uncomfortable, I'm sorry about that.

**Comment by wangwenx190** [comment]
I closed this PR because I think what you said is quite reasonable. People will not benefit much from upgrading the LZMA SDK and it may bing us some unknown risks.

**Pull request closed without merging**
