### PR TITLE
Added MsgBox Designer Tool

### PR DESCRIPTION
**Pull request by leserg73**
With **MsgBox Designer Tool** can add into the script MessageBox code.

MsgBoxDesigner

### CODE REVIEW

**Comment by martijnlaan** [comment]
Thanks, looks useful!

**Comment by martijnlaan** [comment]
Compiled and played with the UI a bit now as well, really nice. One thing I do miss is support for Suppressible(TaskDialog)MsgBox. In fact, I think it should use the Suppressible version by default. Would you be interested in adding support for that?

**Comment by leserg73** [comment]
Ok, I’ll think about how to do this and try to add support for Suppressible(TaskDialog)MsgBox.

**Comment by martijnlaan** [comment]
Cool, thanks!

**Comment by leserg73** [comment]
Added support for creating a suppressible message box (SuppressibleMsgBox and SuppressibleTaskDialogMsgBox).
Also slightly changed the design of the '_MessageBox Designer_' form. I think it will be better and more convenient.

Screenshot 1 (creation MsgBox)
MsgBox

Result code is
```
// Display a message box
MsgBox('<Enter your text here...>', mbInformation, MB_OK);
```

Screenshot 2 (creation SuppressibleMsgBox)
SupprMsgBox

Result code is
```
// Display a message box
SuppressibleMsgBox('<Enter your text here...>', mbInformation, MB_YESNO or MB_DEFBUTTON2 or MB_SETFOREGROUND, IDYES);
```

Screenshot 3 (creation TaskDialogMsgBox)
TaskMsgBox

Result code is
```
// Display a message box
if TaskDialogMsgBox('Instruction Text', 'Messsage Text', mbInformation, MB_YESNOCANCEL, ['Yes', 'No'], IDYES) = IDNO then
begin
  // user clicked NO
end;
```

Screenshot 4 (creation SuppressibleTaskDialogMsgBox)
SupprTaskMsgBox

Result code is
```
// Display a message box
if SuppressibleTaskDialogMsgBox('Instruction Text', 'Messsage Text', mbError, MB_ABORTRETRYIGNORE, ['Retry', 'Ignore', 'Abort'], IDRETRY, IDIGNORE) = IDRETRY then
begin
  // user clicked RETRY
end;
```

Note: my code (_MessageBoxInsert.pas_) is not optimized, as my level of knowledge of Delphi is beginner. Therefore, do not be surprised if you see something strange.

**Comment by martijnlaan** [comment]
Thanks!

**Comment by martijnlaan** [comment]
Did some tweaks and merged it!

**Pull request merged**
