### PR TITLE
Fixing a function TNewLinkLabel.AdjustHeight

### PR DESCRIPTION
**Pull request by leserg73**
LM_GETIDEALSIZE message returns Height for a **given Width**.

### CODE REVIEW

**Comment by martijnlaan** [comment]
But Width is the current width so this should be the same as using GETIDEALHEIGHT? Or are you saying you have seen it fixes the problem which was posted on the forum anyway?

**Comment by jordanrussell** [comment]
Could it be that the `LM_GETIDEALHEIGHT` documentation is just wrong? Wine's implementation simply returns the current font's height, and that looks like what's happening in the forum screen shots as well.

And note that the `LM_GETIDEALSIZE` docs don't say that `lParam` is allowed to be 0.

**Comment by martijnlaan** [comment]
I changed it from LM_GETIDEALSIZE ato LM_GETIDEALHEIGHT in 1d1d6b0854dae4f65414028785e15c1bb5a1e109. Reverted this now since I now see the second doesnt work for me also but the first does. Not sure why and not sure how I missed this back when I did the 'improvement'.

Delphi also has some strange related code I don't understand BTW:

afbeelding

**Comment by martijnlaan** [comment]
Forgot to say, @leserg73 thanks for pointing to the solution!

**Pull request closed without merging**
