### PR TITLE
Update Corsican translation to version 6.0.3

### PR DESCRIPTION
**Pull request by Patriccollu**
@martijnlaan 
Hello,

I just updated the Corsican translation file with new strings and some other minor changes.

Thanks,
Patriccollu.

### CODE REVIEW

**Comment by martijnlaan** [comment]
Grazie!

**Comment by Patriccollu** [comment]
@martijnlaan 
Ti ne pregu ! (_You're welcome!_)

**Comment by martijnlaan** [comment]
@Patriccollu Please note a fix was done to Corsican.isl. It was encoded as UTF-8 but lacked a BOM. This has been fixed now, please make sure to update your local copy if you have one.

**Comment by Patriccollu** [comment]
@martijnlaan Thanks a lot for the fix!

**Pull request merged**
