### PR TITLE
Added Italian language strings

### PR DESCRIPTION
**Pull request by bovirus**

### CODE REVIEW

**Comment by bovirus** [comment]
Please don't include this update.
There is an error about "è" accented letter. Ignore it.

**Comment by bovirus** [comment]
What's the right standard of text file for .iss file?

I made a copy/paste from Inno Setup Compiler but is seems that there are some problems on accented letters.

**Comment by bovirus** [comment]
[setup.zip](https://github.com/jrsoftware/issrc/files/2094623/setup.zip)

I have problem with accented letters.
Please add you the file.
I attached it to the post.
Please check at the end letetrs like è ò.
Thanks.

**Comment by martijnlaan** [comment]
Thanks but I think this really needs to be handled via Git, maintaining languages is already too much work for me. Did you use the GitHub's web editor to make the changes. That doesn't seem to work indeed: it will auto change things into UTF8. So you'll need to use Git itself and a proper editor like Notepad or Notepad++. See https://github.com/jrsoftware/issrc/blob/master/CONTRIBUTING.md for an explanation about how to setup Git.

Will close the pull requests for now.

**Pull request closed without merging**
