### PR TITLE
update lng.file for IS 6.0.0+

### PR DESCRIPTION
**Pull request by AstaRom**

### CODE REVIEW

**Comment by martijnlaan** [comment]
Thanks but when the time is right I will send a message to the maintainers.

**Comment by AstaRom** [comment]
The encoding was incorrect, I will resend.

**Comment by martijnlaan** [comment]
Thanks but don't, I will not accept it, see above.

**Comment by AstaRom** [comment]
What are these "maintainers" for, if you can just now update the translation file for the current changes in the project?

**Comment by AstaRom** [comment]
Or do you think that they will translate better than ordinary users who want to contribute to their favorite software?

**Pull request closed without merging**
